"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, Calculator, CheckCircle2, FileText, Mail, MapPin, Phone, Send } from "lucide-react";
import { projects, services } from "../site-data";

const finishMultipliers = { Standard: 1, Premium: 1.35, Luxury: 1.75 } as const;
type Finish = keyof typeof finishMultipliers;

const formatter = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 });

export default function QuotePage() {
  const [service, setService] = useState(services[0].title);
  const [finish, setFinish] = useState<Finish>("Premium");
  const [size, setSize] = useState(250);
  const [timeline, setTimeline] = useState("Standard");
  const [submitted, setSubmitted] = useState(false);
  const activeService = services.find((item) => item.title === service) ?? services[0];
  const estimate = useMemo(() => {
    const base = activeService.unit.includes("%") ? 15000000 * (activeService.rate / 100) : activeService.rate * Math.max(size, 1);
    const timelineFactor = timeline === "Urgent" ? 1.18 : timeline === "Flexible" ? 0.95 : 1;
    return Math.round(base * finishMultipliers[finish] * timelineFactor);
  }, [activeService, finish, size, timeline]);

  return (
    <main className="min-h-screen bg-[#F5F7FA] text-[#111827]">
      <header className="bg-[#0D3B66] px-5 py-5 text-[#F5F7FA] md:px-8"><nav className="mx-auto flex max-w-7xl items-center justify-between gap-5"><Link href="/" className="flex items-center gap-3"><span className="relative h-12 w-12 overflow-hidden border border-[#8B1E00]/40 bg-[#0D3B66]"><Image src="/Images/LOGO.png" alt="Charismak logo" fill sizes="48px" className="object-contain p-1" /></span><span><span className="block text-sm font-semibold uppercase tracking-[0.24em]">Charismak</span><span className="block text-xs text-[#F5F7FA]/58">Project Nigeria Limited</span></span></Link><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#8B1E00]"><ArrowLeft className="h-4 w-4" /> Home</Link></nav></header>

      <section className="relative bg-[#0D3B66] px-5 py-24 text-[#F5F7FA] md:px-8"><Image src="/Images/Projects/Steel fabrication and civil works (23).jpg" alt="Quote center background" fill priority sizes="100vw" className="object-cover opacity-24" /><div className="absolute inset-0 bg-gradient-to-r from-[#0D3B66] via-[#0D3B66]/92 to-[#0D3B66]/70" /><div className="relative mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#8B1E00]">Client & Visitor Desk</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold tracking-tight md:text-7xl">Request a quote, check rate guidance, and generate an estimate.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#F5F7FA]/70">Use this quote center to start a project enquiry, review service rate guidance, and prepare a preliminary budget before a site inspection.</p></div></section>

      <section className="px-5 py-20 md:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.05fr_0.95fr]">
        <div className="bg-white p-6 shadow-[0_24px_80px_rgba(13,59,102,0.08)] md:p-8"><div className="flex items-center gap-3"><Calculator className="h-7 w-7 text-[#8B1E00]" /><h2 className="text-3xl font-semibold text-[#0D3B66]">Instant Estimate Generator</h2></div><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="block"><span className="text-sm font-semibold text-[#0D3B66]">Service</span><select value={service} onChange={(event) => setService(event.target.value)} className="mt-2 w-full border border-[#0D3B66]/15 bg-[#F5F7FA] px-4 py-3 outline-none focus:border-[#8B1E00]">{services.map((item) => <option key={item.title}>{item.title}</option>)}</select></label><label className="block"><span className="text-sm font-semibold text-[#0D3B66]">Finish Level</span><select value={finish} onChange={(event) => setFinish(event.target.value as Finish)} className="mt-2 w-full border border-[#0D3B66]/15 bg-[#F5F7FA] px-4 py-3 outline-none focus:border-[#8B1E00]"><option>Standard</option><option>Premium</option><option>Luxury</option></select></label><label className="block"><span className="text-sm font-semibold text-[#0D3B66]">Approx. Size / Scope Unit</span><input value={size} onChange={(event) => setSize(Number(event.target.value))} min={1} type="number" className="mt-2 w-full border border-[#0D3B66]/15 bg-[#F5F7FA] px-4 py-3 outline-none focus:border-[#8B1E00]" /></label><label className="block"><span className="text-sm font-semibold text-[#0D3B66]">Timeline</span><select value={timeline} onChange={(event) => setTimeline(event.target.value)} className="mt-2 w-full border border-[#0D3B66]/15 bg-[#F5F7FA] px-4 py-3 outline-none focus:border-[#8B1E00]"><option>Flexible</option><option>Standard</option><option>Urgent</option></select></label></div><div className="mt-8 border border-[#8B1E00]/25 bg-[#0D3B66] p-7 text-[#F5F7FA]"><p className="text-sm uppercase tracking-[0.24em] text-[#8B1E00]">Preliminary Estimate</p><p className="mt-3 text-5xl font-semibold tracking-tight">{formatter.format(estimate)}</p><p className="mt-4 leading-7 text-[#F5F7FA]/65">This is guidance only. Final quotation depends on drawings, site inspection, specification, logistics, material prices, and procurement timing.</p></div></div>

        <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }} className="bg-[#0D3B66] p-6 text-[#F5F7FA] md:p-8"><div className="flex items-center gap-3"><FileText className="h-7 w-7 text-[#8B1E00]" /><h2 className="text-3xl font-semibold">Request Official Quote</h2></div><div className="mt-8 grid gap-4"><input required placeholder="Full name" className="border border-white/10 bg-white/[0.06] px-4 py-3 outline-none placeholder:text-[#F5F7FA]/45 focus:border-[#8B1E00]" /><input required type="email" placeholder="Email address" className="border border-white/10 bg-white/[0.06] px-4 py-3 outline-none placeholder:text-[#F5F7FA]/45 focus:border-[#8B1E00]" /><input required placeholder="Phone / WhatsApp" className="border border-white/10 bg-white/[0.06] px-4 py-3 outline-none placeholder:text-[#F5F7FA]/45 focus:border-[#8B1E00]" /><select className="border border-white/10 bg-[#10233A] px-4 py-3 outline-none focus:border-[#8B1E00]">{projects.map((project) => <option key={project.slug}>{project.title}</option>)}<option>New Custom Project</option></select><textarea required placeholder="Tell us about the project, location, budget range, and expected timeline" rows={6} className="border border-white/10 bg-white/[0.06] px-4 py-3 outline-none placeholder:text-[#F5F7FA]/45 focus:border-[#8B1E00]" /></div><button className="mt-6 inline-flex w-full items-center justify-center gap-3 bg-[#8B1E00] px-7 py-4 font-semibold text-white transition hover:bg-[#F5F7FA] hover:text-[#0D3B66]">Submit Quote Request <Send className="h-5 w-5" /></button>{submitted && <div className="mt-5 flex gap-3 border border-[#8B1E00]/30 bg-white/[0.06] p-4 text-sm text-[#F5F7FA]/75"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#8B1E00]" /> Your request has been prepared. Connect this form to email, CRM, or backend storage for live submissions.</div>}</form>
      </div></section>

      <section className="bg-white px-5 py-20 md:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#8B1E00]">Rate Guidance</p><h2 className="mt-5 text-4xl font-semibold tracking-tight text-[#0D3B66]">Current service rate guide</h2></div><p className="max-w-xl leading-7 text-[#111827]/66">These rates are indicative and should be validated against drawings, site conditions, quantity survey, market changes, and specification level.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{services.map((item) => <article key={item.title} className="border border-[#0D3B66]/10 bg-[#F5F7FA] p-6"><item.icon className="h-7 w-7 text-[#8B1E00]" /><h3 className="mt-8 text-xl font-semibold text-[#0D3B66]">{item.title}</h3><p className="mt-3 text-2xl font-semibold text-[#0D3B66]">{item.unit.includes("%") ? `${item.rate}%` : formatter.format(item.rate)}</p><p className="mt-2 text-sm text-[#111827]/62">{item.unit}</p></article>)}</div></div></section>

      <footer className="bg-[#0D3B66] px-5 py-10 text-[#F5F7FA] md:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.24em]">Charismak Project Nigeria Limited</p><p className="mt-2 text-sm text-[#F5F7FA]/55">Premium construction enquiries and visitor quote center.</p></div><div className="space-y-2 text-sm text-[#F5F7FA]/65"><p className="flex items-center gap-3"><MapPin className="h-4 w-4 text-[#8B1E00]" /> Nigeria</p><p className="flex items-center gap-3"><Mail className="h-4 w-4 text-[#8B1E00]" /> info@charismakprojects.com</p><p className="flex items-center gap-3"><Phone className="h-4 w-4 text-[#8B1E00]" /> Premium project enquiries</p></div></div></footer>
    </main>
  );
}

